import { NextResponse } from 'next/server';
import { COLLECTIONS, ensureSeedData, getSorrDb, verifySorrSession } from '@/lib/sorr/controlui-server';

function makeAuditId() {
  return `AUD-${Date.now()}-${Math.floor(Math.random() * 900 + 100)}`;
}

function fallbackDraft(requestData, policyBundle) {
  return [
    `Request ID: ${requestData.id}`,
    `Use Case: ${requestData.useCaseName || 'Unknown'}`,
    `Risk Tier: ${policyBundle.riskLabel || `Tier ${requestData.tier}`}`,
    '',
    'Proposed structured response:',
    '1. Acknowledge the customer concern and summarise known facts.',
    '2. Confirm what evidence was reviewed and what checks remain open.',
    '3. Provide a policy-aligned proposed action and approval boundary.',
    '4. Add next contact timeline and accountable owner.',
    '',
    'Compliance controls:',
    `- Permitted tools: ${(policyBundle.permittedTools || []).join(', ') || 'none'}`,
    `- Blocked actions: ${(policyBundle.blockedActions || []).join(', ') || 'none'}`,
  ].join('\n');
}

async function generateClaudeDraft(requestData, policyBundle) {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) return null;

  const model = process.env.SORR_ANTHROPIC_MODEL || 'claude-3-5-sonnet-latest';
  const response = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'content-type': 'application/json',
      'x-api-key': apiKey,
      'anthropic-version': '2023-06-01',
    },
    body: JSON.stringify({
      model,
      max_tokens: 700,
      temperature: 0.2,
      system:
        'You draft enterprise responses under strict policy controls. Keep output concise and professional. Do not invent actions listed as blocked.',
      messages: [
        {
          role: 'user',
          content: [
            {
              type: 'text',
              text:
                `Create a draft output for this classified request.\n` +
                `Request:\n${requestData.prompt}\n\n` +
                `Route: ${requestData.route}\n` +
                `Risk tier: ${requestData.tier}\n` +
                `Permitted tools: ${(policyBundle.permittedTools || []).join(', ')}\n` +
                `Blocked actions: ${(policyBundle.blockedActions || []).join(', ')}`,
            },
          ],
        },
      ],
    }),
  });

  if (!response.ok) return null;
  const data = await response.json();
  const text = Array.isArray(data?.content) ? data.content.map((part) => part?.text || '').join('\n\n').trim() : '';
  return text || null;
}

export async function POST(request) {
  const auth = await verifySorrSession(request);
  if (!auth.authenticated) {
    return NextResponse.json({ error: auth.error }, { status: 401 });
  }

  try {
    const body = await request.json();
    const requestId = String(body?.requestId || '').trim();
    if (!requestId) {
      return NextResponse.json({ error: 'requestId is required.' }, { status: 400 });
    }

    const { db } = await getSorrDb();
    await ensureSeedData(db);

    const requestRef = db.collection(COLLECTIONS.requests).doc(requestId);
    const policyRef = db.collection(COLLECTIONS.policyBundles).doc(requestId);
    const [requestSnap, policySnap] = await Promise.all([requestRef.get(), policyRef.get()]);

    if (!requestSnap.exists) return NextResponse.json({ error: 'Request not found.' }, { status: 404 });

    const requestData = { id: requestSnap.id, ...(requestSnap.data() || {}) };
    const policyBundle = policySnap.exists ? policySnap.data() || {} : {};

    const status = String(requestData.status || '');
    if (!['APPROVED', 'COMPLETED'].includes(status)) {
      return NextResponse.json({ error: 'Draft generation requires an APPROVED or COMPLETED request.' }, { status: 409 });
    }

    const claudeText = await generateClaudeDraft(requestData, policyBundle);
    const draft = claudeText || fallbackDraft(requestData, policyBundle);
    const provider = claudeText ? 'claude' : 'fallback';
    const now = new Date();

    await requestRef.set(
      {
        latestDraft: draft,
        latestDraftProvider: provider,
        updatedAt: now,
      },
      { merge: true }
    );

    await db.collection(COLLECTIONS.auditLog).doc(makeAuditId()).set({
      requestId,
      actor: auth.user.email,
      action: 'DRAFT_GENERATED',
      detail: `Draft generated by ${provider}.`,
      tier: Number(requestData.tier || 4),
      createdAt: now,
    });

    return NextResponse.json(
      {
        requestId,
        provider,
        draft,
      },
      { status: 200 }
    );
  } catch (error) {
    console.error('[SoRR Control draft] failed', error);
    return NextResponse.json({ error: 'Failed to generate draft.' }, { status: 500 });
  }
}
